-- MySQL Script generated by MySQL Workbench
-- Fri May 20 04:08:04 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projetotcc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projetotcc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetotcc` DEFAULT CHARACTER SET utf8 ;
USE `projetotcc` ;

-- -----------------------------------------------------
-- Table `projetotcc`.`DIM_tempo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetotcc`.`DIM_tempo` (
  `id_tempo` INT NOT NULL AUTO_INCREMENT,
  `ano` INT NULL,
  PRIMARY KEY (`id_tempo`));


-- -----------------------------------------------------
-- Table `projetotcc`.`DIM_local`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetotcc`.`DIM_local` (
  `id_local` INT NOT NULL AUTO_INCREMENT,
  `regiao` VARCHAR(45) NULL,
  `uf` VARCHAR(2) NULL,
  PRIMARY KEY (`id_local`));


-- -----------------------------------------------------
-- Table `projetotcc`.`fato_recursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetotcc`.`fato_recursos` (
  `quant_obitos` INT NULL,
  `quant_respiradores` INT NULL,
  `quant_respiradores_sus` INT NULL,
  `quant_uti_adulto` INT NULL,
  `quant_uti_adulto_sus` INT NULL,
  `quant_uti_sup_pulmonar` INT NULL,
  `quant_uti_sup_pulmonar_sus` INT NULL,
  `quant_populacao_total` INT NULL,
  `quant_populacao_dep_privada` INT NULL,
  `quant_populacao_dep_sus` INT NULL,
  `DIM_local_id_local` INT NOT NULL,
  `DIM_tempo_id_tempo` INT NOT NULL,
  PRIMARY KEY (`DIM_local_id_local`, `DIM_tempo_id_tempo`),
  INDEX `fk_Fato_DIM_local1_idx` (`DIM_local_id_local` ASC),
  INDEX `fk_Fato_DIM_tempo1_idx` (`DIM_tempo_id_tempo` ASC),
  CONSTRAINT `fk_Fato_DIM_local1`
    FOREIGN KEY (`DIM_local_id_local`)
    REFERENCES `projetotcc`.`DIM_local` (`id_local`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fato_DIM_tempo1`
    FOREIGN KEY (`DIM_tempo_id_tempo`)
    REFERENCES `projetotcc`.`DIM_tempo` (`id_tempo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `projetotcc`.`DIM_obitos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetotcc`.`DIM_obitos` (
  `id_obitos` INT NOT NULL AUTO_INCREMENT,
  `local_obito` VARCHAR(255) NULL,
  `faixa_etaria` VARCHAR(45) NULL,
  `sexo` VARCHAR(1) NULL,
  PRIMARY KEY (`id_obitos`));


-- -----------------------------------------------------
-- Table `projetotcc`.`fato_obitos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetotcc`.`fato_obitos` (
  `DIM_obitos_id_obitos` INT NOT NULL,
  `DIM_tempo_id_tempo` INT NOT NULL,
  `DIM_local_id_local` INT NOT NULL,
  `quant_obitos` INT NULL,
  PRIMARY KEY (`DIM_obitos_id_obitos`, `DIM_tempo_id_tempo`, `DIM_local_id_local`),
  INDEX `fk_fato_Obitos_DIM_tempo1_idx` (`DIM_tempo_id_tempo` ASC),
  INDEX `fk_fato_Obitos_DIM_local1_idx` (`DIM_local_id_local` ASC),
  CONSTRAINT `fk_fato_Obitos_DIM_obitos1`
    FOREIGN KEY (`DIM_obitos_id_obitos`)
    REFERENCES `projetotcc`.`DIM_obitos` (`id_obitos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fato_Obitos_DIM_tempo1`
    FOREIGN KEY (`DIM_tempo_id_tempo`)
    REFERENCES `projetotcc`.`DIM_tempo` (`id_tempo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fato_Obitos_DIM_local1`
    FOREIGN KEY (`DIM_local_id_local`)
    REFERENCES `projetotcc`.`DIM_local` (`id_local`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
